version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 11.4.1
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          path: vendor/bundle
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - run:
          name: Bundle update
          command: bundle update fastlane
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: 11.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE: beta
    steps:
      - checkout
      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          path: vendor/bundle
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - run:
          name: Bundle update
          command: bundle update fastlane
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - add_ssh_keys:
          fingerprints:
            - "e0:bb:f5:45:80:6f:94:df:51:ee:67:b9:dd:d4:8c:ba"
            - "f8:8d:55:8e:04:67:a9:69:e6:6e:09:4d:e5:ea:fa:89"
      - run:
          name: Install Firebase Tools
          command: npm install firebase-tools
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE
      - store_artifacts:
          path: output

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      - beta:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
