version: 2.1
jobs:
  unit-test:
    macos:
      xcode: 12.0.0
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE: unittest
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Ruby バージョンの設定
          command: echo 'chruby ruby-2.6' >> ~/.bash_profile # 2.6 を特定の Ruby バージョンに置き換え
      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          path: vendor/bundle
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - run:
          name: Bundle update
          command: bundle update fastlane
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: 12.0.0
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE: beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: ruby version
          command: echo 'chruby ruby-2.6' >> ~/.bash_profile
      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          path: vendor/bundle
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - run:
          name: Bundle update
          command: bundle update fastlane
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - add_ssh_keys:
          fingerprints:
            - "a5:d7:ae:3b:25:d7:8d:23:75:e2:4f:e5:a5:58:70:e5"
            - "f8:8d:55:8e:04:67:a9:69:e6:6e:09:4d:e5:ea:fa:89"
      - run:
          name: firebase tools
          command: curl -sL https://firebase.tools | bash
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE
          no_output_timeout: 15m
      - store_artifacts:
          path: output/DevMemo.app.dSYM.zip
      - store_artifacts:
          path: output/DevMemo.ipa
workflows:
  build-adhoc:
    jobs:
      - beta:
          filters:
            branches:
              only: master
  build-test:
    jobs:
      - unit-test
