# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

skip_binary_upload false
ipa "./build/ipa/DevMemo.ipa"
apple_id "i.kawashima41.dev@gmail.com"